### ISSUE TITLE
When will the code be public?

### ISSUE THREAD

**Issue by matri123** [donggong1/learn-optimizer-rgdn#1]
Hello, I am very interested in your work, I hope refer to your code for further research. And hope to quote your paper, when will you release the code. If it is not convenient to release now, can we use the mail to further communicate, thanks. My email is falling47@hotmail.com

**Comment by donggong1** [comment]
Sorry for delay, and thanks for your interest. The code has been uploaded couple of weeks ago. Please feel free to contact me if you have any question.
